execute if block ~ ~ ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~ ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~1 ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~1 ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~-1 ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~-1 ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~1 ~ ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~1 ~ ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~ ~1 lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~ ~1 lava run function poke/blocks/lava_sponge_to_molten
execute if block ~-1 ~ ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~-1 ~ ~ lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~ ~-1 lava run function poke/blocks/lava_sponge_to_molten
execute if block ~ ~ ~-1 lava run function poke/blocks/lava_sponge_to_molten